version: "3.9"
services:
  webapi:
    build:
      context: .
      dockerfile: FiapOrders.WebApi/FiapOrders.WebApi/Dockerfile
    ports:
      - "5000:8080"
    environment:
      RabbitMq.HostName: rabbitmq
      RabbitMq.Username: guest
      RabbitMq.Password: guest
    depends_on:
      - rabbitmq
  data:
    build:
      context: .
      dockerfile: FiapOrders.Data/FiapOrders.Data/Dockerfile
    environment:
      RabbitMq.HostName: rabbitmq
      RabbitMq.Username: guest
      RabbitMq.Password: guest
      MongoDb.ConnectionString: mongodb://root:example@mongo:27017/
      MongoDb.Database: FiapOrders
    depends_on:
      - rabbitmq
      - mongo
  rabbitmq:   
    image: "masstransit/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example